apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-gateway
  labels:
    app: msvc-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-gateway
  template:
    metadata:
      labels:
        app: msvc-gateway
    spec:
      containers:
        - name: msvc-gateway
          image: formidata/microservice-gateway:v1.1.0
          ports:
            - containerPort: 8081
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: "k8s"