apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: msvc-gateway-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: gateway.local
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: msvc-gateway
                port:
                  number: 8081