apiVersion: v1
kind: Service
metadata:
  name: msvc-gateway
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8081"
spec:
  type: NodePort
  selector:
    app: msvc-gateway
  ports:
    - port: 8081         # Puerto del servicio dentro del clúster
      targetPort: 8081   # Puerto del contenedor (tu app Spring Boot)
      nodePort: 30881     # Puerto del nodo (Minikube) — localhost:8081