apiVersion: v1
kind: Service
metadata:
  name: inventario-servicio
spec:
  type: NodePort
  selector:
    app: inventario-servicio
  ports:
    - port: 8083         # Puerto del servicio dentro del clúster
      targetPort: 8083   # Puerto del contenedor (tu app Spring Boot)
      nodePort: 30083     # Puerto del nodo (Minikube) — localhost:8081