apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuario-servicio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usuario-servicio
  template:
    metadata:
      labels:
        app: usuario-servicio
    spec:
      containers:
      - name: usuario-servicio-container
        image: formidata/usuario-servicio:v1.1.3
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
