apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuario-servicio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usuario-servicio
  template:
    metadata:
      labels:
        app: usuario-servicio
    spec:
      containers:
      - name: usuario-servicio-container
        image: formidata/usuario-servicio:v1.0.2
        ports:
        - containerPort: 8082
