apiVersion: v1
kind: Service
metadata:
  name: usuario-servicio
spec:
  type: NodePort
  selector:
    app: usuario-servicio
  ports:
    - port: 8082         # Puerto del servicio dentro del clúster
      targetPort: 8082   # Puerto del contenedor (tu app Spring Boot)
      nodePort: 30082     # Puerto del nodo (Minikube) — localhost:8081
