apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-script
data:
  init.sql: |
    SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
    START TRANSACTION;
    SET time_zone = "+00:00";

    CREATE DATABASE IF NOT EXISTS usuarios;
    USE usuarios;

    CREATE TABLE `log_acceso` (
      `id` bigint(20) NOT NULL,
      `accion` varchar(255) DEFAULT NULL,
      `fecha_hora` datetime(6) DEFAULT NULL,
      `usuario_id` bigint(20) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

    INSERT INTO `log_acceso` (`id`, `accion`, `fecha_hora`, `usuario_id`) VALUES
    (1, 'Entrar', '2025-05-15 02:53:23.000000', 2);

    CREATE TABLE `rol` (
      `id` bigint(20) NOT NULL,
      `tipo` varchar(255) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

    INSERT INTO `rol` (`id`, `tipo`) VALUES
    (1, 'administrador');

    CREATE TABLE `usuario` (
      `id` bigint(20) NOT NULL,
      `apellido` varchar(255) DEFAULT NULL,
      `contrasena` varchar(255) DEFAULT NULL,
      `correo` varchar(255) DEFAULT NULL,
      `nombre` varchar(255) DEFAULT NULL,
      `rol_id` bigint(20) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

    INSERT INTO `usuario` (`id`, `apellido`, `contrasena`, `correo`, `nombre`, `rol_id`) VALUES
    (2, 'Gómez', '123456', 'ana@example.com', 'Ana', 1);

    ALTER TABLE `log_acceso`
      ADD PRIMARY KEY (`id`),
      ADD KEY `FKsl6w0x2iid5j7mny1tl5xwu14` (`usuario_id`);

    ALTER TABLE `rol`
      ADD PRIMARY KEY (`id`);

    ALTER TABLE `usuario`
      ADD PRIMARY KEY (`id`),
      ADD KEY `FKshkwj12wg6vkm6iuwhvcfpct8` (`rol_id_
