apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-eureka
  labels:
    app: msvc-eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-eureka
  template:
    metadata:
      labels:
        app: msvc-eureka
    spec:
      containers:
        - name: msvc-eureka
          image: formidata/microservice-eureka:v1.0.1
          ports:
            - containerPort: 8761