apiVersion: v1
kind: Service
metadata:
  name: msvc-eureka
spec:
  type: NodePort
  selector:
    app: msvc-eureka
  ports:
    - port: 8761         # Puerto del servicio dentro del clúster
      targetPort: 8761  # Puerto del contenedor (tu app Spring Boot)
      nodePort: 30081     # Puerto del nodo (Minikube) — localhost:8081